# Generated by Django 5.0.4 on 2024-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Задание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
            ],
            options={
                'verbose_name': 'одно задание',
                'verbose_name_plural': 'много заданий',
            },
        ),
    ]
